#!/usr/bin/env python
import rospy
import sys

from hrr_cobot_robot.ros_nodes_click_commands import start_controller

rospy.init_node("start_controller")

if start_controller():
    sys.exit(1)
sys.exit(0)
