#!/usr/bin/env python

import rospy
import tf2_ros

from geometry_msgs.msg import PointStamped

rospy.init_node("ee_visualizer")

REF_FRAME = rospy.get_param("base_frame", "base_link")
DUMMY_FRAME = rospy.get_param("base_frame", "wsg_50_tcp")

tf_buffer = tf2_ros.Buffer()
tf2_ros.TransformListener(tf_buffer)

ee_viz_pub = rospy.Publisher('ee_dummy', PointStamped, queue_size=100)

r = rospy.Rate(250)


def get_tcp_pos(link_name, trials=10):
    for _ in range(trials):
        try:
            trans_msg = tf_buffer.lookup_transform(REF_FRAME, link_name, rospy.Time(0))
            return trans_msg.transform.translation
        except (tf2_ros.LookupException, tf2_ros.ConnectivityException, tf2_ros.ExtrapolationException):
            r.sleep()
            continue


while not rospy.is_shutdown():
    pos_msg = PointStamped()
    pos_msg.header.frame_id = REF_FRAME
    pos_msg.point = get_tcp_pos(DUMMY_FRAME)
    ee_viz_pub.publish(pos_msg)
    r.sleep()
