#!/usr/bin/env python3

import rospy
from sensor_msgs.msg import JointState

from hrr_common.ros_utils.helper_handles import get_param
from hrr_common.simple_joint_state_publisher import CompleteJointStatePublisher


def main():
    joint_state_publisher = CompleteJointStatePublisher(parameter_prefix="~")
    if not joint_state_publisher.initialized:
        rospy.logerr(f"[{rospy.get_name()}] joint state publisher could not be initialized. Shutting down node")
        return
    while not rospy.is_shutdown():
        joint_state_publisher.update()


if __name__ == "__main__":
    rospy.init_node("simple_joint_state_publisher")
    main()
